pool: default

trigger:
  branches:
    include:
      - dev

variables:
  - group: 'Common Variables'

name: $(Version.Major).$(Version.Minor)$(Rev:.r)

steps:
  - task: Cache@2
    inputs:
      key: yarn | $(Agent.OS) | azure-extensions
      path: $(YARN_CACHE_FOLDER)
      cacheHitVar: 'CACHED_DEPS'
      restoreKeys: |
        yarn | $(Agent.OS) | azure-extensions
        yarn | $(Agent.OS)
        yarn
    displayName: Dependency Cache

  - script: yarn install
    displayName: Install Dependencies
    workingDirectory: $(WorkspacePath)

  - script: yarn test
    displayName: Run Unit Tests
    workingDirectory: $(WorkspacePath)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'

  - script: yarn build --cli-version $(Version.Major).$(Version.Minor)$(Rev:.r)
    displayName: Build Sources
    workingDirectory: $(WorkspacePath)

  - script: yarn bundle
    displayName: Bundle Extensions
    workingDirectory: $(WorkspacePath)

  - script: yarn run publish # This MUST use `yarn run ...` since `publish` is for NPM publishing
    displayName: Publish Extensions
    workingDirectory: $(WorkspacePath)
    env:
      TFX_PUBLISH_TOKEN: $(Tfx.Token)
