pool: default

trigger:
  branches:
    include:
      - dev
  paths:
    exclude:
      - .wiki

variables:
  - group: 'Common Variables'

name: $(Version.Major).$(Version.Minor)$(Rev:.r)

steps:
  - script: yarn install
    displayName: Install Dependencies
    workingDirectory: $(WorkspacePath)

  - script: yarn test
    displayName: Run Unit Tests
    workingDirectory: $(WorkspacePath)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'

  - script: yarn build --cli-version $(Build.BuildNumber)
    displayName: Build Sources
    workingDirectory: $(WorkspacePath)

  - script: yarn bundle
    displayName: Bundle Extensions
    workingDirectory: $(WorkspacePath)

  - script: yarn run publish # This MUST use `yarn run ...` since `publish` is for NPM publishing
    displayName: Publish Extensions
    workingDirectory: $(WorkspacePath)
    env:
      TFX_PUBLISH_TOKEN: $(Tfx.Token)

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: '$(WorkspacePath)/.bundled'
      ArtifactName: 'bundles'
      publishLocation: 'Container'
